version: '3.5'

networks:
  conda-net:
    name: my-conda-net
    driver: bridge

volumes:
  conda-storage:

services:
  miniconda:
    image: miniconda3:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - conda-storage:/home
