name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - scipy
  - pip
  - pip:
    - datetime
    - openpyxl
    - mysql-connector-python
    - pyyaml
    - pandas
    - numpy
    - requests
    - beautifulsoup4
